name: hello_dart

description: >-
  Aprendiendo Dart desde cero: sintaxis, pruebas personales y retos de programación.

environment:
  sdk: '^3.8.0'
  
dependencies:
  characters: ^1.4.0
  color: ^3.0.0
  meta: ^1.17.0
