name: hello_dart

description: >-
  Aprendiendo Dart desde cero: sintaxis, pruebas personales y retos de programación.

environment:
  sdk: '^3.8.0'
  
dependencies:
  characters: ^1.4.0
  color: ^3.0.0
  file: ^7.0.1
  http: ^1.4.0
  meta: ^1.17.0
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3
